# Generated by Django 5.2.4 on 2025-07-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsApp',
        ),
    ]
