# Generated by Django 5.2.4 on 2025-07-16 16:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsapp',
            name='headline',
        ),
        migrations.AlterField(
            model_name='newsapp',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
