# Generated by Django 5.2.4 on 2025-07-17 06:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_newsapp_headline_alter_newsapp_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='newSlug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
