# Generated by Django 4.1.13 on 2025-07-21 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_subcategory_remove_category_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubCategory_name',
            new_name='subcategory_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category'),
            preserve_default=False,
        ),
    ]
