# Generated by Django 4.1.13 on 2025-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='produt_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
