# Generated by Django 4.1.13 on 2025-07-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariant',
            old_name='prize',
            new_name='prise',
        ),
        migrations.RenameField(
            model_name='sizevatiant',
            old_name='prize',
            new_name='prise',
        ),
    ]
