# Generated by Django 5.2.4 on 2025-07-18 19:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerTitle', models.CharField(max_length=400)),
                ('bannerDis', tinymce.models.HTMLField()),
                ('bannerImg', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
