# Generated by Django 5.2.4 on 2025-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivaity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
