# Generated by Django 5.2.4 on 2025-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='temp_field',
            field=models.CharField(default='temp', max_length=10),
        ),
    ]
