# Generated by Django 5.2.4 on 2025-07-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_temp_field'),
    ]

    operations = [
    ]
