# Generated by Django 5.2.4 on 2025-07-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20250716_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='temp_field',
        ),
    ]
