# Generated by Django 5.2.4 on 2025-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='explore_images/'),
        ),
    ]
